name: Deployment

on:
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - 'tiny-shields-worker/**'

defaults:
  run:
    working-directory: tiny-shields-worker

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Bundle
        run: npm run build

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'tiny-shields-worker'
